#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════╗
# ║  DCI Swarm — LLM Provider Detection                            ║
# ║  Checks which LLM providers are available and writes config     ║
# ╚══════════════════════════════════════════════════════════════════╝
#
# Usage: ./swarm-kit/detect-llm.sh
# Output: swarm-kit/.llm-providers.yaml
# Exit: 0 if at least one provider found, 1 if none

set -euo pipefail

# Source user's shell profile to pick up API keys set there
if [ -f "$HOME/.zshrc" ]; then
    set +eu  # zshrc may have unset vars or failing commands
    source "$HOME/.zshrc" 2>/dev/null || true
    set -eu
elif [ -f "$HOME/.bashrc" ]; then
    set +eu
    source "$HOME/.bashrc" 2>/dev/null || true
    set -eu
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_FILE="$SCRIPT_DIR/.llm-providers.yaml"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BOLD='\033[1m'
NC='\033[0m'

providers_found=0

echo -e "${BOLD}DCI Swarm — LLM Provider Detection${NC}"
echo ""

# Start YAML output
cat > "$OUTPUT_FILE" <<EOF
# Auto-generated by detect-llm.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Re-run ./swarm-kit/detect-llm.sh to refresh
providers:
EOF

# --- Claude CLI ---
if command -v claude &>/dev/null; then
    echo -e "  ${GREEN}[found]${NC}  Claude CLI (claude)"
    cat >> "$OUTPUT_FILE" <<EOF
  - name: claude-cli
    type: cli
    command: claude
    priority: 1
    status: available
EOF
    providers_found=$((providers_found + 1))
else
    echo -e "  ${YELLOW}[missing]${NC} Claude CLI — install from https://claude.ai/claude-code"
fi

# --- Codex CLI / ChatGPT CLI / macOS App ---
if command -v codex &>/dev/null; then
    echo -e "  ${GREEN}[found]${NC}  Codex CLI (codex)"
    cat >> "$OUTPUT_FILE" <<EOF
  - name: codex-cli
    type: cli
    command: codex
    priority: 2
    status: available
EOF
    providers_found=$((providers_found + 1))
elif command -v chatgpt &>/dev/null; then
    echo -e "  ${GREEN}[found]${NC}  ChatGPT CLI (chatgpt)"
    cat >> "$OUTPUT_FILE" <<EOF
  - name: chatgpt-cli
    type: cli
    command: chatgpt
    priority: 2
    status: available
EOF
    providers_found=$((providers_found + 1))
elif [ -d "/Applications/ChatGPT.app" ]; then
    echo -e "  ${GREEN}[found]${NC}  ChatGPT macOS app (CLI not in PATH)"
    echo -e "         ${YELLOW}Tip:${NC} Install Codex CLI: brew install openai-codex"
    cat >> "$OUTPUT_FILE" <<EOF
  - name: chatgpt-app
    type: macos-app
    path: /Applications/ChatGPT.app
    cli_installed: false
    priority: 2
    status: available_no_cli
    note: "App installed but no CLI in PATH. Install Codex CLI: brew install openai-codex"
EOF
    providers_found=$((providers_found + 1))
else
    echo -e "  ${YELLOW}[missing]${NC} Codex CLI / ChatGPT CLI / macOS app"
fi

# --- GitHub Copilot CLI ---
if command -v gh &>/dev/null && gh copilot --help &>/dev/null 2>&1; then
    echo -e "  ${GREEN}[found]${NC}  GitHub Copilot CLI (gh copilot)"
    cat >> "$OUTPUT_FILE" <<EOF
  - name: gh-copilot-cli
    type: cli
    command: gh copilot
    priority: 2
    status: available
EOF
    providers_found=$((providers_found + 1))
else
    echo -e "  ${YELLOW}[missing]${NC} GitHub Copilot CLI — install gh CLI + copilot extension"
fi

# --- Cursor ---
if [ -d "/Applications/Cursor.app" ]; then
    echo -e "  ${GREEN}[found]${NC}  Cursor IDE (/Applications/Cursor.app)"
    cat >> "$OUTPUT_FILE" <<EOF
  - name: cursor
    type: ide
    path: /Applications/Cursor.app
    priority: 6
    status: available
    note: "IDE with built-in LLM support. Not usable as a CLI agent runner but available for interactive development."
EOF
    providers_found=$((providers_found + 1))
elif command -v cursor &>/dev/null; then
    echo -e "  ${GREEN}[found]${NC}  Cursor IDE (cursor CLI)"
    cat >> "$OUTPUT_FILE" <<EOF
  - name: cursor
    type: ide
    command: cursor
    priority: 6
    status: available
EOF
    providers_found=$((providers_found + 1))
else
    echo -e "  ${YELLOW}[missing]${NC} Cursor IDE"
fi

# --- Anthropic API Key ---
if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
    echo -e "  ${GREEN}[found]${NC}  Anthropic API (ANTHROPIC_API_KEY set)"
    cat >> "$OUTPUT_FILE" <<EOF
  - name: anthropic-api
    type: api
    env_var: ANTHROPIC_API_KEY
    priority: 3
    status: available
EOF
    providers_found=$((providers_found + 1))
else
    echo -e "  ${YELLOW}[missing]${NC} Anthropic API — set ANTHROPIC_API_KEY"
fi

# --- OpenAI API Key ---
if [ -n "${OPENAI_API_KEY:-}" ]; then
    echo -e "  ${GREEN}[found]${NC}  OpenAI API (OPENAI_API_KEY set)"
    cat >> "$OUTPUT_FILE" <<EOF
  - name: openai-api
    type: api
    env_var: OPENAI_API_KEY
    priority: 4
    status: available
EOF
    providers_found=$((providers_found + 1))
else
    echo -e "  ${YELLOW}[missing]${NC} OpenAI API — set OPENAI_API_KEY"
fi

# --- Ollama ---
if curl -s --connect-timeout 2 http://localhost:11434/api/tags &>/dev/null; then
    echo -e "  ${GREEN}[found]${NC}  Ollama (localhost:11434)"
    cat >> "$OUTPUT_FILE" <<EOF
  - name: ollama
    type: local
    endpoint: http://localhost:11434
    priority: 5
    status: available
EOF
    providers_found=$((providers_found + 1))
else
    echo -e "  ${YELLOW}[missing]${NC} Ollama — install from https://ollama.ai"
fi

# --- Summary ---
cat >> "$OUTPUT_FILE" <<EOF

summary:
  providers_found: $providers_found
  detected_at: "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
EOF

echo ""
echo -e "Detected ${BOLD}$providers_found${NC} provider(s). Config written to ${OUTPUT_FILE#$SCRIPT_DIR/}"

if [ "$providers_found" -eq 0 ]; then
    echo ""
    echo -e "${RED}No LLM providers found.${NC} The DCI swarm requires at least one provider."
    echo "Install Claude CLI, set an API key, or start Ollama."
    exit 1
fi

exit 0
