"""add performer_id FK on agent_sessions

Revision ID: 0d46323a713e
Revises: 24ce3df3c76c
Create Date: 2026-01-31 02:19:33.530184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d46323a713e'
down_revision: Union[str, Sequence[str], None] = '24ce3df3c76c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_agent_sessions_performer_id', 'performers', ['performer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agent_sessions_performer_id', type_='foreignkey')

    # ### end Alembic commands ###
