"""full schema baseline

Revision ID: 24ce3df3c76c
Revises: 
Create Date: 2026-01-31 02:19:04.356237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24ce3df3c76c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('model_tier', sa.Enum('OPUS', 'SONNET', 'HAIKU', name='modeltier'), nullable=False),
    sa.Column('tools_allowed', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('modified_by', sa.String(length=36), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('corps_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capability_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('performer_id', sa.String(length=36), nullable=True),
    sa.Column('performer_name', sa.String(length=100), nullable=True),
    sa.Column('role_type', sa.String(length=50), nullable=False),
    sa.Column('entry_type', sa.Enum('REP_COMPLETED', 'REP_FAILED', 'SESSION_COMPLETED', 'SESSION_FAILED', 'TRUST_CHANGE', 'RETIREMENT', 'GUPP_VIOLATION', name='ledgerentrytype'), nullable=False),
    sa.Column('corps_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('rep_id', sa.String(length=36), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('trust_before', sa.Float(), nullable=True),
    sa.Column('trust_after', sa.Float(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coordinates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('SHOW', 'MOVEMENT', 'SET', 'COORDINATE', name='coordinatetype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'REVIEW', 'COMPLETED', 'FAILED', 'BLOCKED', name='coordinatestatus'), nullable=False),
    sa.Column('caption', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['coordinates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('show_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('INITIALIZING', 'REHEARSAL', 'TOUR', 'COMPLETED', 'DISBANDED', name='corpsstatus'), nullable=False),
    sa.Column('rehearsal_mode', sa.Enum('BASICS', 'SECTIONALS', 'FULL_ENSEMBLE', 'RUN_THROUGH', name='rehearsalmode'), nullable=True),
    sa.Column('tour_mode', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role_type', sa.String(length=50), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('successful_sessions', sa.Integer(), nullable=False),
    sa.Column('failed_sessions', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PROBATION', 'RETIRED', name='performerstatus'), nullable=False),
    sa.Column('specialties', sa.Text(), nullable=True),
    sa.Column('retirement_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('performers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performers_role_type'), ['role_type'], unique=False)

    op.create_table('shows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='showstatus'), nullable=False),
    sa.Column('corps_id', sa.String(length=36), nullable=True),
    sa.Column('coordinate_root_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('corps_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_logs_corps_id'), ['corps_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_logs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('agent_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('definition_id', sa.String(length=36), nullable=False),
    sa.Column('corps_id', sa.String(length=36), nullable=False),
    sa.Column('parent_session_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'FAILED', 'TIMED_OUT', name='sessionstatus'), nullable=False),
    sa.Column('context_snapshot', sa.Text(), nullable=True),
    sa.Column('performer_id', sa.String(length=36), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['agent_definitions.id'], ),
    sa.ForeignKeyConstraint(['parent_session_id'], ['agent_sessions.id'], ),
    sa.ForeignKeyConstraint(['performer_id'], ['performers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('corps_id', sa.String(length=36), nullable=False),
    sa.Column('from_role', sa.String(length=50), nullable=False),
    sa.Column('from_session_id', sa.String(length=36), nullable=True),
    sa.Column('to_role', sa.String(length=50), nullable=True),
    sa.Column('to_session_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('HANDOFF', 'ESCALATION', 'FLAG', 'STATUS', 'DIRECTIVE', 'FEEDBACK', name='messagetype'), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'NORMAL', 'LOW', name='messagepriority'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('coordinate_id', sa.String(length=36), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['coordinate_id'], ['coordinates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problems',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('coordinate_id', sa.String(length=36), nullable=False),
    sa.Column('corps_id', sa.String(length=36), nullable=False),
    sa.Column('reported_by_role', sa.String(length=50), nullable=False),
    sa.Column('reported_by_session_id', sa.String(length=36), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='problemseverity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='problemstatus'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by_role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coordinate_id'], ['coordinates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('coordinate_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'REVIEW', 'COMPLETED', 'FAILED', name='repstatus'), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['coordinate_id'], ['coordinates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('coordinate_id', sa.String(length=36), nullable=False),
    sa.Column('subscriber_role', sa.String(length=50), nullable=False),
    sa.Column('subscriber_session_id', sa.String(length=36), nullable=True),
    sa.Column('corps_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('REP_COMPLETED', 'REP_FAILED', 'REP_ASSIGNED', 'COORDINATE_COMPLETED', 'COORDINATE_FAILED', 'PROBLEM_POSTED', 'PROBLEM_RESOLVED', name='eventtype'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['coordinate_id'], ['coordinates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penalties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('corps_id', sa.String(length=36), nullable=False),
    sa.Column('rep_id', sa.String(length=36), nullable=True),
    sa.Column('coordinate_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('TIMING', 'BUDGET', 'RULE', name='penaltytype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('issued_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['coordinate_id'], ['coordinates.id'], ),
    sa.ForeignKeyConstraint(['rep_id'], ['reps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rep_id', sa.String(length=36), nullable=True),
    sa.Column('coordinate_id', sa.String(length=36), nullable=True),
    sa.Column('corps_id', sa.String(length=36), nullable=False),
    sa.Column('judge_type', sa.Enum('BRASS', 'PERCUSSION', 'GUARD', 'VISUAL', 'GENERAL_EFFECT', 'TIMING', name='judgetype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('box', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['coordinate_id'], ['coordinates.id'], ),
    sa.ForeignKeyConstraint(['rep_id'], ['reps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('penalties')
    op.drop_table('subscriptions')
    op.drop_table('reps')
    op.drop_table('problems')
    op.drop_table('messages')
    op.drop_table('agent_sessions')
    with op.batch_alter_table('work_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_work_logs_session_id'))
        batch_op.drop_index(batch_op.f('ix_work_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_work_logs_corps_id'))

    op.drop_table('work_logs')
    op.drop_table('shows')
    with op.batch_alter_table('performers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performers_role_type'))

    op.drop_table('performers')
    op.drop_table('corps')
    op.drop_table('coordinates')
    op.drop_table('capability_ledger')
    op.drop_table('agent_definitions')
    # ### end Alembic commands ###
