"""add_reps_table

Revision ID: 4fc336742c84
Revises: 57901e98cbc0
Create Date: 2026-02-01 02:15:29.036599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc336742c84'
down_revision: Union[str, Sequence[str], None] = '57901e98cbc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messaging_threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('corps_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('initiator_agent_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key(None, 'agent_sessions', ['initiator_agent_id'], ['id'])
        batch_op.create_foreign_key(None, 'corps', ['corps_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messaging_threads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('viewed_at')
        batch_op.drop_column('initiator_agent_id')
        batch_op.drop_column('corps_id')

    # ### end Alembic commands ###
