"""sync schema: remove deprecated tables and fix enum types

Revision ID: 5717763b1040
Revises: 4d42d37fd13c
Create Date: 2026-02-01 01:53:38.674896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5717763b1040'
down_revision: Union[str, Sequence[str], None] = '4d42d37fd13c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_memory_agent_identity'))
        batch_op.drop_index(batch_op.f('ix_task_memory_session_id'))
        batch_op.drop_index(batch_op.f('ix_task_memory_task_hash'))

    op.drop_table('task_memory')
    with op.batch_alter_table('agent_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_memory_agent_identity'))

    op.drop_table('agent_memory')
    op.drop_table('self_improvement_log')
    op.drop_table('agent_experience')
    with op.batch_alter_table('agent_definitions', schema=None) as batch_op:
        batch_op.alter_column('classification',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('performing_member', 'instructional_staff', 'administrative_staff', 'logistics', 'dci_assigned', name='agentclassification'),
               existing_nullable=True)

    with op.batch_alter_table('corps', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('initializing', 'winter_camps', 'on_tour', 'ready_for_contest', 'completed', 'disbanded', name='corpsstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corps', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('initializing', 'winter_camps', 'on_tour', 'ready_for_contest', 'completed', 'disbanded', name='corpsstatus'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)

    with op.batch_alter_table('agent_definitions', schema=None) as batch_op:
        batch_op.alter_column('classification',
               existing_type=sa.Enum('performing_member', 'instructional_staff', 'administrative_staff', 'logistics', 'dci_assigned', name='agentclassification'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)

    op.create_table('agent_experience',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('performer_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('show_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('corps_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('learned_skills', sa.TEXT(), nullable=True),
    sa.Column('achievements', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['performer_id'], ['performers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('self_improvement_log',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('agent_definition_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('old_version', sa.INTEGER(), nullable=False),
    sa.Column('new_version', sa.INTEGER(), nullable=False),
    sa.Column('changes', sa.TEXT(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('approved_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['agent_definition_id'], ['agent_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_memory',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('agent_identity', sa.VARCHAR(length=100), nullable=False),
    sa.Column('memory_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('confidence', sa.FLOAT(), server_default=sa.text("'1.0'"), nullable=False),
    sa.Column('source_session_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('source_task', sa.TEXT(), nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('superseded_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_memory_agent_identity'), ['agent_identity'], unique=False)

    op.create_table('task_memory',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('agent_identity', sa.VARCHAR(length=100), nullable=False),
    sa.Column('task_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('tool_calls', sa.TEXT(), nullable=True),
    sa.Column('outcomes', sa.TEXT(), nullable=True),
    sa.Column('checkpoints', sa.TEXT(), nullable=True),
    sa.Column('result_summary', sa.TEXT(), nullable=True),
    sa.Column('success', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_memory_task_hash'), ['task_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_memory_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_memory_agent_identity'), ['agent_identity'], unique=False)

    # ### end Alembic commands ###
